-- Insert SQL Rules Here 
INSERT INTO Projects	(ProjectType,									Name,													ShortName,													Description,													Cost,	CostProgressionModel,				CostProgressionParam1,	PrereqDistrict,					AdvisorType) VALUES
						('PROJECT_ENHANCE_DISTRICT_SOUQ',				'LOC_PROJECT_ENHANCE_DISTRICT_SOUQ_NAME',				'LOC_PROJECT_ENHANCE_DISTRICT_SOUQ_SHORT_NAME',				'LOC_PROJECT_ENHANCE_DISTRICT_SHOPPING_COMPLEX_DESCRIPTION',	'125',	'COST_PROGRESSION_GAME_PROGRESS',	'1500',					'DISTRICT_SOUQ',				'ADVISOR_GENERIC'),
						('PROJECT_ENHANCE_DISTRICT_SHOPPING_COMPLEX',	'LOC_PROJECT_ENHANCE_DISTRICT_SHOPPING_COMPLEX_NAME',	'LOC_PROJECT_ENHANCE_DISTRICT_SHOPPING_COMPLEX_SHORT_NAME',	'LOC_PROJECT_ENHANCE_DISTRICT_SHOPPING_COMPLEX_DESCRIPTION',	'125',	'COST_PROGRESSION_GAME_PROGRESS',	'1500',					'DISTRICT_SHOPPING_COMPLEX',	'ADVISOR_GENERIC');

INSERT INTO Project_YieldConversions	(ProjectType,									YieldType,		PercentOfProductionRate) VALUES
										('PROJECT_ENHANCE_DISTRICT_SOUQ',				'YIELD_GOLD',	'15'),
										('PROJECT_ENHANCE_DISTRICT_SHOPPING_COMPLEX',	'YIELD_GOLD',	'15');

INSERT INTO Project_GreatPersonPoints	(ProjectType,									GreatPersonClassType,			Points, PointProgressionModel,				PointProgressionParam1) VALUES
										('PROJECT_ENHANCE_DISTRICT_SOUQ',				'GREAT_PERSON_CLASS_MERCHANT',	'2',	'COST_PROGRESSION_GAME_PROGRESS',	'800'),
										('PROJECT_ENHANCE_DISTRICT_SHOPPING_COMPLEX',	'GREAT_PERSON_CLASS_MERCHANT',	'2',	'COST_PROGRESSION_GAME_PROGRESS',	'800');
						