-- New Beliefs
/*INSERT INTO Beliefs (BeliefType,						Name,										Description,								BeliefClassType)VALUES
					-- Worship
					('BELIEF_BASILICA',					'LOC_BELIEF_BASILICA_NAME',					'LOC_BELIEF_BASILICA_DESC',					'BELIEF_CLASS_WORSHIP'),
					('BELIEF_CHAPEL',					'LOC_BELIEF_CHAPEL_NAME',					'LOC_BELIEF_CHAPEL_DESC',					'BELIEF_CLASS_WORSHIP'),
					('BELIEF_MITHRAEUM',				'LOC_BELIEF_MITHRAEUM_NAME',				'LOC_BELIEF_MITHRAEUM_DESC',				'BELIEF_CLASS_WORSHIP'),
					('BELIEF_HUSSAINIYA',				'LOC_BELIEF_HUSSAINIYA_NAME',				'LOC_BELIEF_HUSSAINIYA_DESC',				'BELIEF_CLASS_WORSHIP'),
					('BELIEF_MARTYRIUM',				'LOC_BELIEF_MARTYRIUM_NAME',				'LOC_BELIEF_MARTYRIUM_DESC',				'BELIEF_CLASS_WORSHIP'),
					-- Follower
					('BELIEF_RELIGOUS_TRADE',			'LOC_BELIEF_RELIGOUS_TRADE_NAME',			'LOC_BELIEF_RELIGOUS_TRADE_DESC',			'BELIEF_CLASS_FOLLOWER'),
					('BELIEF_JESUIT_MISSIONARIES',		'LOC_BELIEF_JESUIT_MISSIONARIES_NAME',		'LOC_BELIEF_JESUIT_MISSIONARIES_DESC',		'BELIEF_CLASS_FOLLOWER'),
					('BELIEF_PIOUS_ARIATOCRACY',		'LOC_BELIEF_PIOUS_ARIATOCRACY_NAME',		'LOC_BELIEF_PIOUS_ARIATOCRACY_DESC',		'BELIEF_CLASS_FOLLOWER'),
					('BELIEF_PIOUS_ARMY',				'LOC_BELIEF_PIOUS_ARMY_NAME',				'LOC_BELIEF_PIOUS_ARMY_DESC',				'BELIEF_CLASS_FOLLOWER'),
					('BELIEF_RELIGOUS_ABUNDANCE',		'LOC_BELIEF_RELIGOUS_ABUNDANCE_NAME',		'LOC_BELIEF_RELIGOUS_ABUNDANCE_DESC',		'BELIEF_CLASS_FOLLOWER');*/
-- New Modifiers
INSERT INTO BeliefModifiers	(BeliefType,								ModifierId)VALUES 
							-- Enhancer
							-- Founder
							-- Worship
							-- Follower
							-- Pantheons
							('BELIEF_DANCE_OF_THE_AURORA',				'DANCE_OF_THE_AURORA_TUNDRA_FOOD'),
							('BELIEF_DESERT_FOLKLORE',					'DESERT_FOLKLORE_DESERT_FOOD'),
							('BELIEF_DIVINE_SPARK',						'DIVINE_SPARK_WONDER_FAITH'),
							('BELIEF_GOD_OF_CRAFTSMEN',					'GOD_OF_CRAFTSMEN_MERCHANT_PROD'),
							('BELIEF_GOD_OF_CRAFTSMEN',					'GOD_OF_CRAFTSMEN_SOUQ_PROD'),
							('BELIEF_GOD_OF_THE_SEA',					'GOD_OF_THE_SEA_FOOD'),
							('BELIEF_GODDESS_OF_FESTIVALS',				'GODDESS_OF_FESTIVALS_CITY_CENTER_CULTURE'),
							('BELIEF_GODDESS_OF_THE_HARVEST',			'GODDESS_OF_THE_HARVEST_BONUS_FOOD'),
							('BELIEF_GODDESS_OF_THE_HARVEST',			'GODDESS_OF_THE_HARVEST_BONUS_FAITH'),
							('BELIEF_LADY_OF_THE_REEDS_AND_MARSHES',	'LADY_OF_THE_REEDS_AND_MARSHES_FOOD'),
							('BELIEF_MONUMENT_TO_THE_GODS',				'MONUMENT_TO_THE_GODS_CULTURE'),
							('BELIEF_ORAL_TRADITION',					'ORAL_TRADITION_LUXUARY_CULTURE'),
							('BELIEF_RELIGIOUS_IDOLS',					'RELIGIOUS_IDOLS_MINES_FAITH'),
							('BELIEF_RELIGIOUS_SETTLEMENTS',			'RELIGIOUS_SETTLEMENTS_CITY_CENTER_FAITH'),
							('BELIEF_RIVER_GODDESS',					'RIVER_GODDESS_RIVER_FOOD'),
							('BELIEF_SACRED_PATH',						'SACRED_PATH_FOREST_FAITH'),
							('BELIEF_GOD_OF_THE_OPEN_SKY',				'GOD_OF_THE_OPEN_SKY_PASTURE_FOOD');


INSERT INTO Modifiers	(ModifierId,												ModifierType,											RunOnce,	Permanent,	OwnerRequirementSetId,	SubjectRequirementSetId) VALUES	
						-- Enhancer
						-- Founder
						-- Worship
						-- Follower
						-- Pantheons
						('DANCE_OF_THE_AURORA_TUNDRA_FOOD',							'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',					'0',		'0',		NULL,					'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
						('DANCE_OF_THE_AURORA_TUNDRA_FOOD_MODIFIER',				'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',			'0',		'0',		NULL,					'PLOT_IS_TUNDRA'),
						('DESERT_FOLKLORE_DESERT_FOOD',								'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',					'0',		'0',		NULL,					'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
						('DESERT_FOLKLORE_DESERT_FOOD_MODIFIER',					'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',			'0',		'0',		NULL,					'PLOT_IS_DESERT_TOT'),
						('DIVINE_SPARK_WONDER_FAITH',								'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',					'0',		'0',		NULL,					'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
						('DIVINE_SPARK_WONDER_FAITH_MODIFIER',						'MODIFIER_SINGLE_CITY_ADJUST_WONDER_YIELD_CHANGE',		'0',		'0',		NULL,					NULL),
						('GOD_OF_CRAFTSMEN_MERCHANT_PROD',							'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',					'0',		'0',		NULL,					'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
						('GOD_OF_CRAFTSMEN_MERCHANT_PROD_MODIFIER',					'MODIFIER_BELIEF_CITIES_ADJUST_DISTRICT_YIELD',			'0',		'0',		NULL,					'PLOT_IS_DISTRICT_MERCHANT'),
						('GOD_OF_CRAFTSMEN_SOUQ_PROD',								'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',					'0',		'0',		NULL,					'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
						('GOD_OF_CRAFTSMEN_SOUQ_PROD_MODIFIER',						'MODIFIER_BELIEF_CITIES_ADJUST_DISTRICT_YIELD',			'0',		'0',		NULL,					'PLOT_IS_DISTRICT_SOUQ'),
						('GOD_OF_THE_SEA_FOOD',										'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',					'0',		'0',		NULL,					'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
						('GOD_OF_THE_SEA_FOOD_MODIFIER',							'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',			'0',		'0',		NULL,					'PLOT_HAS_FISHINGBOATS_REQUIREMENTS'),
						('GODDESS_OF_FESTIVALS_CITY_CENTER_CULTURE',				'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',					'0',		'0',		NULL,					'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
						('GODDESS_OF_FESTIVALS_CITY_CENTER_CULTURE_MODIFIER',		'MODIFIER_BELIEF_CITIES_ADJUST_DISTRICT_YIELD',			'0',		'0',		NULL,					'PLOT_IS_CITY_CENTER'),
						('GODDESS_OF_THE_HARVEST_BONUS_FOOD',						'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',					'0',		'0',		NULL,					'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
						('GODDESS_OF_THE_HARVEST_BONUS_FOOD_MODIFIER',				'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',			'0',		'0',		NULL,					'PLOT_HAS_BONUS_RESOURCE'),
						('GODDESS_OF_THE_HARVEST_BONUS_FAITH',						'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',					'0',		'0',		NULL,					'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
						('GODDESS_OF_THE_HARVEST_BONUS_FAITH_MODIFIER',				'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',			'0',		'0',		NULL,					'PLOT_HAS_BONUS_RESOURCE'),
						('LADY_OF_THE_REEDS_AND_MARSHES_FOOD',						'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',					'0',		'0',		NULL,					'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
						('LADY_OF_THE_REEDS_AND_MARSHES_FOOD_MODIFIER',				'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',			'0',		'0',		NULL,					'PLOT_HAS_REEDS_REQUIREMENTS'),
						('MONUMENT_TO_THE_GODS_CULTURE',							'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',					'0',		'0',		NULL,					'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
						('MONUMENT_TO_THE_GODS_CULTURE_MODIFIER',					'MODIFIER_BELIEF_CITIES_ADJUST_BUILDING_YIELD',			'0',		'0',		NULL,					NULL),
						('ORAL_TRADITION_LUXUARY_CULTURE',							'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',					'0',		'0',		NULL,					'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
						('ORAL_TRADITION_LUXUARY_CULTURE_MODIFIER',					'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',			'0',		'0',		NULL,					'PLOT_HAS_LUXURY_RESOURCE'),
						('RELIGIOUS_IDOLS_MINES_FAITH',								'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',					'0',		'0',		NULL,					'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
						('RELIGIOUS_IDOLS_MINES_FAITH_MODIFIER',					'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',			'0',		'0',		NULL,					'PLOT_HAS_IMPROVEMENT_MINE'),
						('RELIGIOUS_SETTLEMENTS_CITY_CENTER_FAITH',					'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',					'0',		'0',		NULL,					'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
						('RELIGIOUS_SETTLEMENTS_CITY_CENTER_FAITH_MODIFIER',		'MODIFIER_BELIEF_CITIES_ADJUST_DISTRICT_YIELD',			'0',		'0',		NULL,					'PLOT_IS_CITY_CENTER'),
						('RIVER_GODDESS_RIVER_FOOD',								'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',					'0',		'0',		NULL,					'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
						('RIVER_GODDESS_RIVER_FOOD_MODIFIER',						'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',			'0',		'0',		NULL,					'PLOT_HAS_FARM_NEXT_RIVER'),
						('SACRED_PATH_FOREST_FAITH',								'MODIFIER_ALL_CITIES_FEATURE_ADJACENCY',				'0',		'0',		NULL,					'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
						('GOD_OF_THE_OPEN_SKY_PASTURE_FOOD',						'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',					'0',		'0',		NULL,					'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
						('GOD_OF_THE_OPEN_SKY_PASTURE_FOOD_MODIFIER',				'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',			'0',		'0',		NULL,					'PLOT_HAS_PASTURE_REQUIREMENTS');


INSERT INTO ModifierArguments	(ModifierId,													Name,			Type,				Value,															Extra) VALUES
								-- Enhancer
								-- Founder
								-- Worship
								-- Follower
								-- Pantheons
								('DANCE_OF_THE_AURORA_TUNDRA_FOOD',								'ModifierId',	'ARGTYPE_IDENTITY', 'DANCE_OF_THE_AURORA_TUNDRA_FOOD_MODIFIER',						NULL),
								('DANCE_OF_THE_AURORA_TUNDRA_FOOD_MODIFIER',					'Amount',		'ARGTYPE_IDENTITY', '1',															NULL),
								('DANCE_OF_THE_AURORA_TUNDRA_FOOD_MODIFIER',					'YieldType',	'ARGTYPE_IDENTITY', 'YIELD_FOOD',													NULL),
								('DESERT_FOLKLORE_DESERT_FOOD',									'ModifierId',	'ARGTYPE_IDENTITY', 'DESERT_FOLKLORE_DESERT_FOOD_MODIFIER',							NULL),
								('DESERT_FOLKLORE_DESERT_FOOD_MODIFIER',						'Amount',		'ARGTYPE_IDENTITY', '1',															NULL),
								('DESERT_FOLKLORE_DESERT_FOOD_MODIFIER',						'YieldType',	'ARGTYPE_IDENTITY', 'YIELD_FOOD',													NULL),
								('DIVINE_SPARK_WONDER_FAITH',									'ModifierId',	'ARGTYPE_IDENTITY', 'DIVINE_SPARK_WONDER_FAITH_MODIFIER',							NULL),
								('DIVINE_SPARK_WONDER_FAITH_MODIFIER',							'Amount',		'ARGTYPE_IDENTITY', '2',															NULL),
								('DIVINE_SPARK_WONDER_FAITH_MODIFIER',							'YieldType',	'ARGTYPE_IDENTITY', 'YIELD_FAITH',													NULL),
								('GOD_OF_CRAFTSMEN_MERCHANT_PROD',								'ModifierId',	'ARGTYPE_IDENTITY', 'GOD_OF_CRAFTSMEN_MERCHANT_PROD_MODIFIER',						NULL),
								('GOD_OF_CRAFTSMEN_MERCHANT_PROD_MODIFIER',						'Amount',		'ARGTYPE_IDENTITY', '2',															NULL),
								('GOD_OF_CRAFTSMEN_MERCHANT_PROD_MODIFIER',						'YieldType',	'ARGTYPE_IDENTITY', 'YIELD_PRODUCTION',												NULL),
								('GOD_OF_CRAFTSMEN_MERCHANT_PROD',								'Description',	'ARGTYPE_IDENTITY', 'LOC_DISTRICT_MERCHANT_PRODUCTION',								NULL),
								('GOD_OF_CRAFTSMEN_SOUQ_PROD',									'ModifierId',	'ARGTYPE_IDENTITY', 'GOD_OF_CRAFTSMEN_SOUQ_PROD_MODIFIER',							NULL),
								('GOD_OF_CRAFTSMEN_SOUQ_PROD_MODIFIER',							'Amount',		'ARGTYPE_IDENTITY', '2',															NULL),
								('GOD_OF_CRAFTSMEN_SOUQ_PROD_MODIFIER',							'YieldType',	'ARGTYPE_IDENTITY', 'YIELD_PRODUCTION',												NULL),
								('GOD_OF_CRAFTSMEN_SOUQ_PROD',									'Description',	'ARGTYPE_IDENTITY', 'LOC_DISTRICT_SOUQ_PRODUCTION',									NULL),
								('GOD_OF_THE_SEA_FOOD',											'ModifierId',	'ARGTYPE_IDENTITY', 'GOD_OF_THE_SEA_FOOD_MODIFIER',									NULL),
								('GOD_OF_THE_SEA_FOOD_MODIFIER',								'Amount',		'ARGTYPE_IDENTITY', '1',															NULL),
								('GOD_OF_THE_SEA_FOOD_MODIFIER',								'YieldType',	'ARGTYPE_IDENTITY', 'YIELD_FOOD',													NULL),
								('GODDESS_OF_FESTIVALS_CITY_CENTER_CULTURE',					'ModifierId',	'ARGTYPE_IDENTITY', 'GODDESS_OF_FESTIVALS_CITY_CENTER_CULTURE_MODIFIER',			NULL),
								('GODDESS_OF_FESTIVALS_CITY_CENTER_CULTURE_MODIFIER',			'Amount',		'ARGTYPE_IDENTITY', '2',															NULL),
								('GODDESS_OF_FESTIVALS_CITY_CENTER_CULTURE_MODIFIER',			'YieldType',	'ARGTYPE_IDENTITY', 'YIELD_FAITH',												NULL),
								('GODDESS_OF_FESTIVALS_CITY_CENTER_CULTURE',					'Description',	'ARGTYPE_IDENTITY', 'LOC_DISTRICT_CITY_CENTER_CULTURE',								NULL),
								('GODDESS_OF_THE_HARVEST_BONUS_FOOD',							'ModifierId',	'ARGTYPE_IDENTITY', 'GODDESS_OF_THE_HARVEST_BONUS_FOOD_MODIFIER',					NULL),
								('GODDESS_OF_THE_HARVEST_BONUS_FOOD_MODIFIER',					'Amount',		'ARGTYPE_IDENTITY', '1',															NULL),
								('GODDESS_OF_THE_HARVEST_BONUS_FOOD_MODIFIER',					'YieldType',	'ARGTYPE_IDENTITY', 'YIELD_FOOD',													NULL),
								('GODDESS_OF_THE_HARVEST_BONUS_FAITH',							'ModifierId',	'ARGTYPE_IDENTITY', 'GODDESS_OF_THE_HARVEST_BONUS_FAITH_MODIFIER',					NULL),
								('GODDESS_OF_THE_HARVEST_BONUS_FAITH_MODIFIER',					'Amount',		'ARGTYPE_IDENTITY', '1',															NULL),
								('GODDESS_OF_THE_HARVEST_BONUS_FAITH_MODIFIER',					'YieldType',	'ARGTYPE_IDENTITY', 'YIELD_FAITH',													NULL),
								('LADY_OF_THE_REEDS_AND_MARSHES_FOOD',							'ModifierId',	'ARGTYPE_IDENTITY', 'LADY_OF_THE_REEDS_AND_MARSHES_FOOD_MODIFIER',					NULL),
								('LADY_OF_THE_REEDS_AND_MARSHES_FOOD_MODIFIER',					'Amount',		'ARGTYPE_IDENTITY', '1',															NULL),
								('LADY_OF_THE_REEDS_AND_MARSHES_FOOD_MODIFIER',					'YieldType',	'ARGTYPE_IDENTITY', 'YIELD_FOOD',													NULL),
								('MONUMENT_TO_THE_GODS_CULTURE',								'ModifierId',	'ARGTYPE_IDENTITY', 'MONUMENT_TO_THE_GODS_CULTURE_MODIFIER',						NULL),
								('MONUMENT_TO_THE_GODS_CULTURE_MODIFIER',						'BuildingType',	'ARGTYPE_IDENTITY', 'BUILDING_MONUMENT',											NULL),
								('MONUMENT_TO_THE_GODS_CULTURE_MODIFIER',						'Amount',		'ARGTYPE_IDENTITY', '1',															NULL),
								('MONUMENT_TO_THE_GODS_CULTURE_MODIFIER',						'YieldType',	'ARGTYPE_IDENTITY', 'YIELD_FAITH',												NULL),
								('ORAL_TRADITION_LUXUARY_CULTURE',								'ModifierId',	'ARGTYPE_IDENTITY', 'ORAL_TRADITION_LUXUARY_CULTURE_MODIFIER',						NULL),
								('ORAL_TRADITION_LUXUARY_CULTURE_MODIFIER',						'Amount',		'ARGTYPE_IDENTITY', '1',															NULL),
								('ORAL_TRADITION_LUXUARY_CULTURE_MODIFIER',						'YieldType',	'ARGTYPE_IDENTITY', 'YIELD_FAITH',													NULL),
								('RELIGIOUS_IDOLS_MINES_FAITH',									'ModifierId',	'ARGTYPE_IDENTITY', 'RELIGIOUS_IDOLS_MINES_FAITH_MODIFIER',							NULL),
								('RELIGIOUS_IDOLS_MINES_FAITH_MODIFIER',						'Amount',		'ARGTYPE_IDENTITY', '1',															NULL),
								('RELIGIOUS_IDOLS_MINES_FAITH_MODIFIER',						'YieldType',	'ARGTYPE_IDENTITY', 'YIELD_FAITH',													NULL),
								('RELIGIOUS_SETTLEMENTS_CITY_CENTER_FAITH',						'ModifierId',	'ARGTYPE_IDENTITY', 'RELIGIOUS_SETTLEMENTS_CITY_CENTER_FAITH_MODIFIER',				NULL),
								('RELIGIOUS_SETTLEMENTS_CITY_CENTER_FAITH_MODIFIER',			'Amount',		'ARGTYPE_IDENTITY', '1',															NULL),
								('RELIGIOUS_SETTLEMENTS_CITY_CENTER_FAITH_MODIFIER',			'YieldType',	'ARGTYPE_IDENTITY', 'YIELD_FAITH',													NULL),
								('RELIGIOUS_SETTLEMENTS_CITY_CENTER_FAITH',						'Description',	'ARGTYPE_IDENTITY', 'LOC_DISTRICT_CITY_CENTER_FAITH',								NULL),
								('RIVER_GODDESS_RIVER_FOOD',									'ModifierId',	'ARGTYPE_IDENTITY', 'RIVER_GODDESS_RIVER_FOOD_MODIFIER',							NULL),
								('RIVER_GODDESS_RIVER_FOOD_MODIFIER',							'Amount',		'ARGTYPE_IDENTITY', '1',															NULL),
								('RIVER_GODDESS_RIVER_FOOD_MODIFIER',							'YieldType',	'ARGTYPE_IDENTITY', 'YIELD_FOOD',													NULL),
								('SACRED_PATH_FOREST_FAITH',									'DistrictType',	'ARGTYPE_IDENTITY', 'DISTRICT_HOLY_SITE',											NULL),
								('SACRED_PATH_FOREST_FAITH',									'FeatureType',	'ARGTYPE_IDENTITY', 'FEATURE_FOREST',												NULL),
								('SACRED_PATH_FOREST_FAITH',									'YieldType',	'ARGTYPE_IDENTITY', 'YIELD_FAITH',													NULL),
								('SACRED_PATH_FOREST_FAITH',									'Amount',		'ARGTYPE_IDENTITY', '2',															NULL),
								('SACRED_PATH_FOREST_FAITH',									'Description',	'ARGTYPE_IDENTITY', 'LOC_FOREST_FAITH',												NULL),
								('GOD_OF_THE_OPEN_SKY_PASTURE_FOOD',							'ModifierId',	'ARGTYPE_IDENTITY', 'GOD_OF_THE_OPEN_SKY_PASTURE_FOOD_MODIFIER',					NULL),
								('GOD_OF_THE_OPEN_SKY_PASTURE_FOOD_MODIFIER',					'Amount',		'ARGTYPE_IDENTITY', '1',															NULL),
								('GOD_OF_THE_OPEN_SKY_PASTURE_FOOD_MODIFIER',					'YieldType',	'ARGTYPE_IDENTITY', 'YIELD_FOOD',													NULL);

-- Remove existing Modifiers
DELETE FROM BeliefModifiers WHERE BeliefType ='BELIEF_GODDESS_OF_THE_HARVEST' AND ModifierId ='GODDESS_OF_THE_HARVEST_HARVEST';
DELETE FROM BeliefModifiers WHERE BeliefType ='BELIEF_GODDESS_OF_THE_HARVEST' AND ModifierId ='GODDESS_OF_THE_HARVEST_REMOVE_FEATURE';
DELETE FROM BeliefModifiers WHERE BeliefType ='BELIEF_ORAL_TRADITION' AND ModifierId ='ORAL_TRADITION_PLANTATION_TAG_CULTURE';
DELETE FROM BeliefModifiers WHERE BeliefType ='BELIEF_RELIGIOUS_IDOLS' AND ModifierId ='RELIGIOUS_IDOLS_BONUS_MINE_FAITH';
DELETE FROM BeliefModifiers WHERE BeliefType ='BELIEF_RELIGIOUS_IDOLS' AND ModifierId ='RELIGIOUS_IDOLS_LUXURY_MINE_FAITH';
-- Update existing Modifiers
UPDATE ModifierArguments SET Value ='15' WHERE ModifierId ='FERTILITY_RITES_GROWTH' AND Name ='Amount';
UPDATE ModifierArguments SET Value ='ERA_MEDIEVAL' WHERE ModifierId ='GOD_OF_THE_FORGE_UNIT_ANCIENT_CLASSICAL_PRODUCTION_MODIFIER' AND Name ='EndEra';
UPDATE ModifierArguments SET Value ='2' WHERE ModifierId ='GODDESS_OF_THE_HUNT_CAMP_FOOD_MODIFIER' AND Name ='Amount';
UPDATE ModifierArguments SET Value ='4' WHERE ModifierId ='STONE_CIRCLES_QUARRY_FAITH_MODIFIER' AND Name ='Amount';
UPDATE ModifierArguments SET Value ='2' WHERE ModifierId ='SACRED_PATH_FAITHFEATUREADJACENCY' AND Name ='Amount';
UPDATE ModifierArguments SET Value ='YIELD_FAITH' WHERE ModifierId ='GOD_OF_THE_OPEN_SKY_PASTURE_CULTURE_MODIFIER' AND Name ='YieldType';

