-- Insert SQL Rules Here 
INSERT INTO TraitModifiers	(TraitType,									ModifierId) VALUES
							('TRAIT_LEADER_MAJOR_CIV',					'SETTLER_START_MOVE_BOOST'),
							('TRAIT_LEADER_MAJOR_CIV',					'SETTLER_START_SIGHT_BOOST'),
							('MINOR_CIV_TRADE_TRAIT',					'SETTLER_START_MOVE_BOOST'),
							('MINOR_CIV_TRADE_TRAIT',					'SETTLER_START_SIGHT_BOOST'),
							('MINOR_CIV_TRADE_TRAIT',					'MINOR_CIV_TRADE_SHOPPING_COMPLEX_PRODUCTION'),
							('TRAIT_CIVILIZATION_ADJACENT_DISTRICTS',	'TRAIT_ADJACENT_DISTRICTS_SHOPPING_COMPLEX_ADJACENCYGOLD'),
							('TRAIT_CIVILIZATION_ADJACENT_DISTRICTS',	'TRAIT_ADJACENT_DISTRICTS_SOUQ_ADJACENCYGOLD');
