-- Reduce range units damage to cities
UPDATE GlobalParameters SET Value ='25' WHERE Name ='COMBAT_DEFENSE_DAMAGE_PERCENT_RANGED';
--Unit Cost
UPDATE Units SET Cost ='90' WHERE UnitType ='UNIT_SETTLER';
UPDATE Units SET Cost ='60' WHERE UnitType ='UNIT_BUILDER';
UPDATE Units SET Cost ='80' WHERE UnitType ='UNIT_TRADER';
UPDATE Units SET Cost ='40' WHERE UnitType ='UNIT_SCOUT';
UPDATE Units SET Cost ='40' WHERE UnitType ='UNIT_WARRIOR';
UPDATE Units SET Cost ='40' WHERE UnitType ='UNIT_SLINGER';
UPDATE Units SET Cost ='80' WHERE UnitType ='UNIT_HORSEMAN';
UPDATE Units SET Cost = Round(Cost * 1.3, 0);
UPDATE Units SET Cost = Round(Cost * 2.2, 0) WHERE UnitType = 'UNIT_MISSIONARY' OR UnitType = 'UNIT_APOSTLE' OR UnitType = 'UNIT_INQUISITOR';
-- Prereq's 
UPDATE units SET RangedCombat ='10' WHERE UnitType ='UNIT_SLINGER';
UPDATE Units SET PrereqTech ='TECH_Exploration' WHERE UnitType ='UNIT_GALLEY';
UPDATE units SET Combat ='20' WHERE UnitType ='UNIT_GALLEY';
UPDATE Units SET PrereqTech ='TECH_SiegeWarfare' WHERE UnitType ='UNIT_CATAPULT';
UPDATE Units SET PrereqTech ='TECH_Sextant' WHERE UnitType ='UNIT_CARAVEL';
UPDATE Units SET PrereqTech ='TECH_HighwaySystems' WHERE UnitType ='UNIT_MODERN_ARMOR';
UPDATE Units SET PrereqTech ='TECH_Marine_Biology' WHERE UnitType ='UNIT_MEDIC';
UPDATE Units SET PrereqCivic ='CIVIC_EARLY_EMPIRE' WHERE UnitType ='UNIT_TRADER';
UPDATE Units SET PrereqTech ='TECH_BRONZE_WORKING' WHERE UnitType ='UNIT_HEAVY_CHARIOT';
UPDATE Units SET PrereqTech ='TECH_BRONZE_WORKING' WHERE UnitType ='UNIT_EGYPTIAN_CHARIOT_ARCHER';
UPDATE Units SET PrereqTech ='TECH_BRONZE_WORKING' WHERE UnitType ='UNIT_SUMERIAN_WAR_CART';
UPDATE Units SET PrereqTech ='TECH_MASONRY' WHERE UnitType ='UNIT_SPEARMAN';
UPDATE Units SET PrereqTech ='TECH_ELECTRICITY' WHERE UnitType ='UNIT_BATTLESHIP';
UPDATE Units SET PrereqTech ='TECH_REPLACEABLE_PARTS' WHERE UnitType ='UNIT_AT_CREW';
UPDATE Units SET PrereqTech ='TECH_RIFLING' WHERE UnitType ='UNIT_CAVALRY';
UPDATE Units SET PrereqTech ='TECH_RIFLING' WHERE UnitType ='UNIT_RUSSIAN_COSSACK';
UPDATE Units SET PrereqTech ='TECH_RIFLING' WHERE UnitType ='UNIT_ENGLISH_REDCOAT';
UPDATE Units SET PrereqTech ='TECH_RIFLING' WHERE UnitType ='UNIT_FRENCH_GARDE_IMPERIALE';
-- Settler and Builder changes
UPDATE Units SET CostProgressionParam1 ='2' WHERE UnitType='UNIT_BUILDER';
UPDATE Units SET PopulationCost ='2' WHERE UnitType='UNIT_SETTLER';
UPDATE Units SET PrereqPopulation ='4' WHERE UnitType='UNIT_SETTLER';
UPDATE Units SET CostProgressionParam1 ='40' WHERE UnitType='UNIT_SETTLER';
-- Upgrade's
DELETE FROM UnitUpgrades WHERE Unit ='UNIT_INFANTRY';
UPDATE UnitUpgrades SET UpgradeUnit ='UNIT_GALLEASS'			WHERE Unit ='UNIT_GALLEY';
UPDATE UnitUpgrades SET UpgradeUnit ='UNIT_GUNBOAT'				WHERE Unit ='UNIT_QUADRIREME';
UPDATE UnitUpgrades SET UpgradeUnit ='UNIT_STEAM_FRIGATE'		WHERE Unit ='UNIT_FRIGATE';
UPDATE UnitUpgrades SET UpgradeUnit ='UNIT_MECHANIZED_INFANTRY' WHERE Unit='UNIT_CAVALRY';
UPDATE UnitUpgrades SET UpgradeUnit ='UNIT_MECHANIZED_INFANTRY' WHERE Unit='UNIT_RUSSIAN_COSSACK';
UPDATE UnitUpgrades SET UpgradeUnit ='UNIT_INFANTRY'			WHERE Unit='UNIT_ENGLISH_REDCOAT';
UPDATE UnitUpgrades SET UpgradeUnit ='UNIT_INFANTRY'			WHERE Unit='UNIT_ENGLISH_REDCOAT';
UPDATE UnitUpgrades SET UpgradeUnit ='UNIT_TANK'				WHERE Unit='UNIT_AMERICAN_ROUGH_RIDER';
-- Start Settler
--UPDATE MajorStartingUnits SET Unit ='UNIT_STARTING_SETTLER' WHERE Unit ='UNIT_SETTLER';
-- Great People
UPDATE GreatPersonIndividuals SET ActionRequiresCompletedDistrictType ='DISTRICT_SHOPPING_COMPLEX' WHERE EraType ='ERA_CLASSICAL' AND ActionRequiresCompletedDistrictType ='DISTRICT_COMMERCIAL_HUB';
UPDATE GreatPersonIndividuals SET ActionRequiresCompletedDistrictType ='DISTRICT_SHOPPING_COMPLEX' WHERE EraType ='ERA_MEDIEVAL' AND ActionRequiresCompletedDistrictType ='DISTRICT_COMMERCIAL_HUB';
UPDATE GreatPersonIndividuals SET ActionRequiresCompletedDistrictType ='DISTRICT_SHOPPING_COMPLEX' WHERE EraType ='ERA_RENAISSANCE' AND ActionRequiresCompletedDistrictType ='DISTRICT_COMMERCIAL_HUB';
UPDATE GreatPersonIndividuals SET ActionRequiresCompletedDistrictType ='DISTRICT_COMMERCIAL_HUB' WHERE GreatPersonIndividualType ='GREAT_PERSON_INDIVIDUAL_GIOVANNI_DE_MEDICI';
--Promotion Class changes
UPDATE Units SET PromotionClass ='PROMOTION_CLASS_LIGHT_CAVALRY' WHERE UnitType ='UNIT_MECHANIZED_INFANTRY';
-- Change Seige units to support formation
UPDATE Units SET PromotionClass ='PROMOTION_CLASS_SIEGE' WHERE UnitType ='UNIT_BATTERING_RAM';
UPDATE Units SET Bombard ='15' WHERE UnitType ='UNIT_BATTERING_RAM';
UPDATE Units SET Range ='1' WHERE UnitType ='UNIT_BATTERING_RAM';
UPDATE Units SET Bombard = Round(Bombard * 1.15, 0);
UPDATE Units SET FormationClass = 'FORMATION_CLASS_SUPPORT' WHERE UnitType ='UNIT_CATAPULT';
UPDATE Units SET FormationClass = 'FORMATION_CLASS_SUPPORT' WHERE UnitType ='UNIT_BOMBARD';
UPDATE Units SET FormationClass = 'FORMATION_CLASS_SUPPORT' WHERE UnitType ='UNIT_ARTILLERY';
UPDATE Units SET FormationClass = 'FORMATION_CLASS_SUPPORT' WHERE UnitType ='UNIT_ROCKET_ARTILLERY';
UPDATE Units SET FormationClass = 'FORMATION_CLASS_SUPPORT' WHERE UnitType ='UNIT_ONAGER';
UPDATE Units SET Combat = '5'	WHERE UnitType ='UNIT_BATTERING_RAM';
UPDATE Units SET Combat = '10'	WHERE UnitType ='UNIT_CATAPULT';
UPDATE Units SET Combat = '10'	WHERE UnitType ='UNIT_ONAGER';
UPDATE Units SET Combat = '15'	WHERE UnitType ='UNIT_BOMBARD';
UPDATE Units SET Combat = '20'	WHERE UnitType ='UNIT_ARTILLERY';
UPDATE Units SET Combat = '25'	WHERE UnitType ='UNIT_ROCKET_ARTILLERY';
UPDATE Units SET CanCapture = '0' WHERE UnitType ='UNIT_CATAPULT';
UPDATE Units SET CanCapture = '0' WHERE UnitType ='UNIT_BOMBARD';
UPDATE Units SET CanCapture = '0' WHERE UnitType ='UNIT_ARTILLERY';
UPDATE Units SET CanCapture = '0' WHERE UnitType ='UNIT_ROCKET_ARTILLERY';
UPDATE Units SET CanCapture = '0' WHERE UnitType ='UNIT_ONAGER';
UPDATE Units SET CanCapture = '0' WHERE UnitType ='UNIT_BATTERING_RAM';
UPDATE Units SET CanCapture = '0' WHERE UnitType ='UNIT_SIEGE_TOWER';

DELETE FROM UnitAiInfos WHERE UnitType='UNIT_CATAPULT'			AND AiType= 'UNITTYPE_LAND_COMBAT';
DELETE FROM UnitAiInfos WHERE UnitType='UNIT_BOMBARD'			AND AiType= 'UNITTYPE_LAND_COMBAT';
DELETE FROM UnitAiInfos WHERE UnitType='UNIT_ARTILLERY'			AND AiType= 'UNITTYPE_LAND_COMBAT';
DELETE FROM UnitAiInfos WHERE UnitType='UNIT_ROCKET_ARTILLERY'	AND AiType= 'UNITTYPE_LAND_COMBAT';

INSERT INTO UnitAiInfos (UnitType, AiType) VALUES
						('UNIT_BATTERING_RAM',		'UNITAI_COMBAT'),
						('UNIT_BATTERING_RAM',		'UNITTYPE_SIEGE');
						--('UNIT_CATAPULT',			'UNITTYPE_SIEGE_SUPPORT'),
						--('UNIT_BOMBARD',			'UNITTYPE_SIEGE_SUPPORT'),
						--('UNIT_ARTILLERY',			'UNITTYPE_SIEGE_SUPPORT'),
						--('UNIT_ROCKET_ARTILLERY',	'UNITTYPE_SIEGE_SUPPORT');
						
DELETE FROM TypeTags WHERE Type ='UNIT_BATTERING_RAM'			AND Tag ='CLASS_BATTERING_RAM';
DELETE FROM TypeTags WHERE Type ='ABILITY_ENABLE_WALL_ATTACK'	AND Tag ='CLASS_BATTERING_RAM';
DELETE FROM TypeTags WHERE Type ='ABILITY_BYPASS_WALLS'			AND Tag ='CLASS_SIEGE_TOWER';
INSERT INTO TypeTags	(Type,							Tag) VALUES
						('UNIT_BATTERING_RAM',			'CLASS_SIEGE'),
						('ABILITY_ENABLE_WALL_ATTACK',	'CLASS_SIEGE_TOWER');

INSERT INTO Unit_BuildingPrereqs	(Unit,			PrereqBuilding,			NumSupported) VALUES
									('UNIT_SCOUT',	'BUILDING_PALACE',		'4');